### ISSUE TITLE
add database mysqle

### ISSUE THREAD

**Issue by UnknownNull** [Gewinum/AuthSystem#2]

**Comment by Gewinum** [comment]
Hello! I have forgot about this repository for a while. If community needs, I can make authsystem, which uses asynchronous sql virion and everything.

**Comment by Gewinum** [comment]
Maybe I'll start working with authsystem soon, idk if i do it now.

**Comment by UnknownNull** [comment]
Add mysql to the plugin as soon as possible. Because your plugin becomes more professional than what it is.
Later, you can add the menu and command during the next updates
Good luck.

**Comment by UnknownNull** [comment]
add cmd for change pass? @Gewinum

**Comment by Gewinum** [comment]
> add cmd for change pass? @Gewinum

i have no time for this plugin yet, sadly

**Comment by Gewinum** [comment]
> add cmd for change pass? @Gewinum

i guess ill do this plugin now, idk..

**Comment by Gewinum** [comment]
> add cmd for change pass? @Gewinum

i am creating auth plugin rn. it uses libasynql now so theres chance it can get to poggit!!!

**Comment by UnknownNull** [comment]
> > add cmd for change pass? @Gewinum
> 
> i am creating auth plugin rn. it uses libasynql now so theres chance it can get to poggit!!!

Please make it so that players cannot create new accounts by changing the upper and lower case letters of their names.

**Comment by UnknownNull** [comment]
If you set the menu and the ability to transfer the player after login the  in the configuration, it will become a unique plugin.
But this plugin will definitely require a command to change the password...

**Comment by Gewinum** [comment]
> If you set the menu and the ability to transfer the player after login the in the configuration, it will become a unique plugin. But this plugin will definitely require a command to change the password...

only in septemba, but will do!!!!

**Comment by Gewinum** [comment]
> If you set the menu and the ability to transfer the player after login the in the configuration, it will become a unique plugin. But this plugin will definitely require a command to change the password...

im interested do this get plugin get accepted.. im currently waiting for poggit accept
